#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : clrtrust
Version  : 0.0.1
Release  : 3
URL      : https://github.com/clearlinux/clrtrust/archive/v0.0.1.tar.gz
Source0  : https://github.com/clearlinux/clrtrust/archive/v0.0.1.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : GPL-2.0
Requires: clrtrust-bin
Requires: openssl
BuildRequires : bats
BuildRequires : openssl

%description
No detailed description available

%package bin
Summary: bin components for the clrtrust package.
Group: Binaries

%description bin
bin components for the clrtrust package.


%prep
%setup -q -n clrtrust-0.0.1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1506720524
make V=1  %{?_smp_mflags}

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make check

%install
export SOURCE_DATE_EPOCH=1506720524
rm -rf %{buildroot}
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/clrtrust
